[workspace]
resolver = "2"
members = [
    "uniproc-linux-agent",
]

[workspace.package]
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.98"

[workspace.dependencies]
anyhow = { version = "1", default-features = false }
libc = { version = "0.2.159", default-features = false }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"
